export const listOfWhos = [
    { id: 1, name: "white rabbit", isRadioSelected: false, isCheckboxSelected: false },
    { id: 2, name: "sister", isRadioSelected: false, isCheckboxSelected: false },
    { id: 3, name: "dinah", isRadioSelected: false, isCheckboxSelected: false },
    { id: 4, name: "mice", isRadioSelected: false, isCheckboxSelected: false },
    { id: 5, name: "cat", isRadioSelected: false, isCheckboxSelected: false },
    { id: 6, name: "mouse", isRadioSelected: false, isCheckboxSelected: false },
    { id: 7, name: "little alice", isRadioSelected: false, isCheckboxSelected: false },
    { id: 8, name: "friends", isRadioSelected: false, isCheckboxSelected: false },
    { id: 9, name: "rabbit", isRadioSelected: false, isCheckboxSelected: false },
    { id: 10, name: "little girl", isRadioSelected: false, isCheckboxSelected: false },
    { id: 11, name: "cats", isRadioSelected: false, isCheckboxSelected: false },
    { id: 12, name: "bats", isRadioSelected: false, isCheckboxSelected: false },
    { id: 13, name: "child", isRadioSelected: false, isCheckboxSelected: false },
    { id: 14, name: "alice", isRadioSelected: false, isCheckboxSelected: false },
    { id: 15, name: "children", isRadioSelected: false, isCheckboxSelected: false }
];

export const listOfWhats = [
    { id: 1, name: "curtain", isRadioSelected: false, isCheckboxSelected: false },
    { id: 2, name: "roast turkeyffee", isRadioSelected: false, isCheckboxSelected: false },
    { id: 3, name: "jar", isRadioSelected: false, isCheckboxSelected: false },
    { id: 4, name: "neck", isRadioSelected: false, isCheckboxSelected: false },
    { id: 5, name: "pictures", isRadioSelected: false, isCheckboxSelected: false },
    { id: 6, name: "bright flowers", isRadioSelected: false, isCheckboxSelected: false },
    { id: 7, name: "beds", isRadioSelected: false, isCheckboxSelected: false },
    { id: 8, name: "glass", isRadioSelected: false, isCheckboxSelected: false },
    { id: 9, name: "little door", isRadioSelected: false, isCheckboxSelected: false },
    { id: 10, name: "key", isRadioSelected: false, isCheckboxSelected: false },
    { id: 11, name: "corner", isRadioSelected: false, isCheckboxSelected: false },
    { id: 12, name: "centre", isRadioSelected: false, isCheckboxSelected: false },
    { id: 13, name: "low", isRadioSelected: false, isCheckboxSelected: false },
    { id: 14, name: "bat", isRadioSelected: false, isCheckboxSelected: false },
    { id: 15, name: "little bottle", isRadioSelected: false, isCheckboxSelected: false },
    { id: 16, name: "door", isRadioSelected: false, isCheckboxSelected: false },
    { id: 17, name: "pink eyes", isRadioSelected: false, isCheckboxSelected: false },
    { id: 18, name: "air", isRadioSelected: false, isCheckboxSelected: false },
    { id: 19, name: "tears", isRadioSelected: false, isCheckboxSelected: false },
    { id: 20, name: "solid glass", isRadioSelected: false, isCheckboxSelected: false },
    { id: 21, name: "red", isRadioSelected: false, isCheckboxSelected: false },
    { id: 22, name: "tunnel", isRadioSelected: false, isCheckboxSelected: false },
    { id: 23, name: "knife", isRadioSelected: false, isCheckboxSelected: false },
    { id: 24, name: "ears", isRadioSelected: false, isCheckboxSelected: false },
    { id: 25, name: "rat", isRadioSelected: false, isCheckboxSelected: false },
    { id: 26, name: "longitude", isRadioSelected: false, isCheckboxSelected: false },
    { id: 27, name: "golden key", isRadioSelected: false, isCheckboxSelected: false },
    { id: 28, name: "tea", isRadioSelected: false, isCheckboxSelected: false },
    { id: 29, name: "daisies", isRadioSelected: false, isCheckboxSelected: false },
    { id: 30, name: "self", isRadioSelected: false, isCheckboxSelected: false },
    { id: 31, name: "waistcoat", isRadioSelected: false, isCheckboxSelected: false },
    { id: 32, name: "apple", isRadioSelected: false, isCheckboxSelected: false },
    { id: 33, name: "telescopes", isRadioSelected: false, isCheckboxSelected: false },
    { id: 34, name: "pine", isRadioSelected: false, isCheckboxSelected: false },
    { id: 35, name: "table", isRadioSelected: false, isCheckboxSelected: false },
    { id: 36, name: "face", isRadioSelected: false, isCheckboxSelected: false },
    { id: 37, name: "legged table", isRadioSelected: false, isCheckboxSelected: false },
    { id: 38, name: "conversations", isRadioSelected: false, isCheckboxSelected: false },
    { id: 39, name: "hand", isRadioSelected: false, isCheckboxSelected: false },
    { id: 40, name: "doors", isRadioSelected: false, isCheckboxSelected: false },
    { id: 41, name: "cake", isRadioSelected: false, isCheckboxSelected: false },
    { id: 42, name: "hole", isRadioSelected: false, isCheckboxSelected: false },
    { id: 43, name: "shoulders", isRadioSelected: false, isCheckboxSelected: false },
    { id: 44, name: "shelves", isRadioSelected: false, isCheckboxSelected: false },
    { id: 45, name: "passage", isRadioSelected: false, isCheckboxSelected: false },
    { id: 46, name: "bottle", isRadioSelected: false, isCheckboxSelected: false },
    { id: 47, name: "watch", isRadioSelected: false, isCheckboxSelected: false },
    { id: 48, name: "tar", isRadioSelected: false, isCheckboxSelected: false },
    { id: 49, name: "daisy", isRadioSelected: false, isCheckboxSelected: false },
    { id: 50, name: "dark", isRadioSelected: false, isCheckboxSelected: false },
    { id: 51, name: "locks", isRadioSelected: false, isCheckboxSelected: false },
    { id: 52, name: "lamps", isRadioSelected: false, isCheckboxSelected: false },
    { id: 53, name: "little glass box", isRadioSelected: false, isCheckboxSelected: false },
    { id: 54, name: "well", isRadioSelected: false, isCheckboxSelected: false },
    { id: 55, name: "dry leaves", isRadioSelected: false, isCheckboxSelected: false },
    { id: 56, name: "finger", isRadioSelected: false, isCheckboxSelected: false },
    { id: 57, name: "toast", isRadioSelected: false, isCheckboxSelected: false },
    { id: 58, name: "book", isRadioSelected: false, isCheckboxSelected: false },
    { id: 59, name: "orange marade", isRadioSelected: false, isCheckboxSelected: false },
    { id: 60, name: "lock", isRadioSelected: false, isCheckboxSelected: false },
    { id: 61, name: "rules", isRadioSelected: false, isCheckboxSelected: false },
    { id: 62, name: "beasts", isRadioSelected: false, isCheckboxSelected: false },
    { id: 63, name: "maps", isRadioSelected: false, isCheckboxSelected: false },
    { id: 64, name: "telescope", isRadioSelected: false, isCheckboxSelected: false },
    { id: 65, name: "currants", isRadioSelected: false, isCheckboxSelected: false },
    { id: 66, name: "poison", isRadioSelected: false, isCheckboxSelected: false },
    { id: 67, name: "heads", isRadioSelected: false, isCheckboxSelected: false },
    { id: 68, name: "roof", isRadioSelected: false, isCheckboxSelected: false },
    { id: 69, name: "sauce", isRadioSelected: false, isCheckboxSelected: false },
    { id: 70, name: "candle", isRadioSelected: false, isCheckboxSelected: false },
    { id: 71, name: "cupboard", isRadioSelected: false, isCheckboxSelected: false },
    { id: 72, name: "paper label", isRadioSelected: false, isCheckboxSelected: false },
    { id: 73, name: "chain", isRadioSelected: false, isCheckboxSelected: false },
    { id: 74, name: "letters", isRadioSelected: false, isCheckboxSelected: false },
    { id: 75, name: "stairs", isRadioSelected: false, isCheckboxSelected: false },
    { id: 76, name: "tiny golden key", isRadioSelected: false, isCheckboxSelected: false },
    { id: 77, name: "little", isRadioSelected: false, isCheckboxSelected: false },
    { id: 78, name: "milk", isRadioSelected: false, isCheckboxSelected: false },
    { id: 79, name: "peg", isRadioSelected: false, isCheckboxSelected: false },
    { id: 80, name: "doorway", isRadioSelected: false, isCheckboxSelected: false },
    { id: 81, name: "feet", isRadioSelected: false, isCheckboxSelected: false },
    { id: 82, name: "eyes", isRadioSelected: false, isCheckboxSelected: false },
    { id: 83, name: "wind", isRadioSelected: false, isCheckboxSelected: false },
    { id: 84, name: "head", isRadioSelected: false, isCheckboxSelected: false },
    { id: 85, name: "flavour", isRadioSelected: false, isCheckboxSelected: false },
    { id: 86, name: "eye", isRadioSelected: false, isCheckboxSelected: false },
    { id: 87, name: "flame", isRadioSelected: false, isCheckboxSelected: false },
    { id: 88, name: "little golden key", isRadioSelected: false, isCheckboxSelected: false },
    { id: 89, name: "latitude", isRadioSelected: false, isCheckboxSelected: false },
    { id: 90, name: "sides", isRadioSelected: false, isCheckboxSelected: false },
    { id: 91, name: "cool fountains", isRadioSelected: false, isCheckboxSelected: false },
    { id: 92, name: "pocket", isRadioSelected: false, isCheckboxSelected: false },
    { id: 93, name: "large rabbit", isRadioSelected: false, isCheckboxSelected: false },
    { id: 94, name: "cherry", isRadioSelected: false, isCheckboxSelected: false },
    { id: 95, name: "croquet", isRadioSelected: false, isCheckboxSelected: false },
    { id: 96, name: "three", isRadioSelected: false, isCheckboxSelected: false },
    { id: 97, name: "row", isRadioSelected: false, isCheckboxSelected: false },
    { id: 98, name: "sticks", isRadioSelected: false, isCheckboxSelected: false },
    { id: 99, name: "histories", isRadioSelected: false, isCheckboxSelected: false },
    { id: 100, name: "legs", isRadioSelected: false, isCheckboxSelected: false },
    { id: 101, name: "wkers", isRadioSelected: false, isCheckboxSelected: false },
    { id: 102, name: "hot poker", isRadioSelected: false, isCheckboxSelected: false }
];

export const listOfWheres = [
    { id: 1, name: "new zealand", isRadioSelected: false, isCheckboxSelected: false },
    { id: 2, name: "well", isRadioSelected: false, isCheckboxSelected: false },
    { id: 3, name: "garden", isRadioSelected: false, isCheckboxSelected: false },
    { id: 4, name: "hedge", isRadioSelected: false, isCheckboxSelected: false },
    { id: 5, name: "schoolroom", isRadioSelected: false, isCheckboxSelected: false },
    { id: 6, name: "earth", isRadioSelected: false, isCheckboxSelected: false },
    { id: 7, name: "australia", isRadioSelected: false, isCheckboxSelected: false },
    { id: 8, name: "house", isRadioSelected: false, isCheckboxSelected: false },
    { id: 9, name: "door", isRadioSelected: false, isCheckboxSelected: false },
    { id: 10, name: "country", isRadioSelected: false, isCheckboxSelected: false },
    { id: 11, name: "bank", isRadioSelected: false, isCheckboxSelected: false },
    { id: 12, name: "hall", isRadioSelected: false, isCheckboxSelected: false },
    { id: 13, name: "field", isRadioSelected: false, isCheckboxSelected: false }
];

export const titleSelectionData = [
    {
        id: 1,
        sentence: "Here Comes Charlie\nThese two very old people are the father and mother of Mr Bucket.",
        primaryWhos: ["charlie", "mr bucket"],
        secondaryWhos: ["bucket", "mother", "people", "father"],
        primaryWhats: ["chair", "car"],
        secondaryWhats: ["value1", "value2"],
        primaryWheres: [],
        secondaryWheres: ["value1", "value2"],
    },
    {
        id: 2,
        sentence: "These two very old people's names are Grandpa Joe and Grandma Josephine.",
        primaryWhos: ["grandpa joe", "grandma josephine"],
        secondaryWhos: ["people"],
        primaryWhats: ["chair", "car"],
        secondaryWhats: [],
        primaryWheres: ["value1", "value2"],
        secondaryWheres: ["value1", "value2"],
    },
    {
        id: 3,
        sentence: "Mr and Mrs Bucket and Charlie slept in the other room, upon mattresses on the floor.",
        primaryWhos: ["charlie", "mrs bucket"],
        secondaryWhos: ["bucket", "mrs", "people", "father"],
        primaryWhats: ["mattress"],
        secondaryWhats: ["room", "floor"],
        primaryWheres: ["value1", "value2"],
        secondaryWheres: [],
    },
    {
        id: 4,
        sentence: "Here Comes Charlie\nThese two very old people are the father and mother of Mr Bucket.",
        primaryWhos: ["charlie", "mr bucket"],
        secondaryWhos: ["bucket", "mother", "people", "father"],
        primaryWhats: ["chair", "car"],
        secondaryWhats: ["value1", "value2"],
        primaryWheres: [],
        secondaryWheres: ["value1", "value2"],
    },
    {
        id: 5,
        sentence: "These two very old people's names are Grandpa Joe and Grandma Josephine.",
        primaryWhos: ["grandpa joe", "grandma josephine"],
        secondaryWhos: ["people"],
        primaryWhats: ["chair", "car"],
        secondaryWhats: [],
        primaryWheres: ["value1", "value2"],
        secondaryWheres: ["value1", "value2"],
    },
];